# SPDX-License-Identifier: GPL-2.0+
#
# (C) Copyright 2020 GlobalLogic

ifdef CONFIG_VIDEO_RENESAS
obj-y += bridge/
obj-y += rcar-du/
obj-y += vsp2/
obj-y += rcar-clk.o
obj-y += rcar-fcp.o
obj-y += rcar-logo.o
endif